// src/pages/products.js
import solarPanelImg from "../assets/solar.png";
import inverterImg from "../assets/inverter.png";
import batteryImg from "../assets/battery.png";
import ledImg from "../assets/led.png";

export const products = [
  {
    id: 1,
    name: "Itel Solar Panel 550W Mono PERC",
    company: "Itel",
    category: "Solar Panels",
    price: 28500,
    image: solarPanelImg,
    description: "High-efficiency mono PERC panel, good low-light performance and 25-year warranty.",
  },
  {
    id: 2,
    name: "Itel Hybrid Inverter 6kW Pro",
    company: "Itel",
    category: "Inverters",
    price: 125000,
    image: inverterImg,
    description: "6kW hybrid with MPPT, WiFi monitoring, battery compatible.",
  },
  {
    id: 3,
    name: "Sofar Hybrid Inverter 5kW",
    company: "Sofar",
    category: "Inverters",
    price: 98000,
    image: inverterImg,
    description: "Smart hybrid inverter with energy storage support.",
  },
  {
    id: 4,
    name: "Sofar On-Grid Inverter 8kW",
    company: "Sofar",
    category: "Inverters",
    price: 145000,
    image: inverterImg,
    description: "High-efficiency on-grid for net metering.",
  },
  {
    id: 5,
    name: "Growatt SPF 5000 ES Hybrid Inverter",
    company: "Growatt",
    category: "Inverters",
    price: 115000,
    image: inverterImg,
    description: "Off-grid/hybrid 5kW, popular for home backup.",
  },
  {
    id: 6,
    name: "Growatt Lithium Battery 5.12kWh",
    company: "Growatt",
    category: "Batteries",
    price: 220000,
    image: batteryImg,
    description: "LiFePO4 battery, 6000+ cycles, wall-mount.",
  },
  {
    id: 7,
    name: "Growatt 550W Solar Panel",
    company: "Growatt",
    category: "Solar Panels",
    price: 32000,
    image: solarPanelImg,
    description: "Mono PERC panel with excellent heat tolerance.",
  },
  {
    id: 8,
    name: "Inverex Nitrox 3kW Hybrid Inverter",
    company: "Inverex",
    category: "Inverters",
    price: 95000,
    image: inverterImg,
    description: "Local favorite hybrid with strong build quality.",
  },
  {
    id: 9,
    name: "Inverex Veyron II 5kW MPPT Inverter",
    company: "Inverex",
    category: "Inverters",
    price: 135000,
    image: inverterImg,
    description: "Reliable MPPT hybrid for residential use.",
  },
  {
    id: 10,
    name: "Inverex 585W N-Type Bifacial Panel",
    company: "Inverex",
    category: "Solar Panels",
    price: 34000,
    image: solarPanelImg,
    description: "Bifacial design for extra energy yield.",
  },
  {
    id: 11,
    name: "Longi Hi-MO 6 550W Mono PERC",
    company: "Longi",
    category: "Solar Panels",
    price: 29500,
    image: solarPanelImg,
    description: "Top-tier efficiency, #1 selling panel in Pakistan.",
  },
  {
    id: 12,
    name: "Longi Hi-MO X6 600W Bifacial",
    company: "Longi",
    category: "Solar Panels",
    price: 38000,
    image: solarPanelImg,
    description: "Advanced bifacial for commercial installs.",
  },
  {
    id: 13,
    name: "Jinko Tiger Neo 580W N-Type",
    company: "Jinko",
    category: "Solar Panels",
    price: 31000,
    image: solarPanelImg,
    description: "High-efficiency N-type with low degradation.",
  },
  {
    id: 14,
    name: "Jinko 610W Mono Facial",
    company: "Jinko",
    category: "Solar Panels",
    price: 33500,
    image: solarPanelImg,
    description: "Reliable performance in hot climates.",
  },
  {
    id: 15,
    name: "Trina Vertex 585W Mono",
    company: "Trina",
    category: "Solar Panels",
    price: 30500,
    image: solarPanelImg,
    description: "Excellent PID resistance and durability.",
  },
  {
    id: 16,
    name: "Huawei SUN2000 5kW On-Grid Inverter",
    company: "Huawei",
    category: "Inverters",
    price: 160000,
    image: inverterImg,
    description: "Smart string inverter with fusion solar app.",
  },
  {
    id: 17,
    name: "Generic Solar LED Street Light 100W",
    company: "Generic",
    category: "Electronics",
    price: 12000,
    image: ledImg,
    description: "Energy-efficient LED with solar panel.",
  },
  {
    id: 18,
    name: "Generic Tubular Battery 200Ah",
    company: "Generic",
    category: "Batteries",
    price: 45000,
    image: batteryImg,
    description: "Affordable backup battery option.",
  },
];